#pragma checksum "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0a00cff60e6561b20225a30caa7a12c5d7ac4107"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Areas_Admin_Views_AdminRelatorioVendas_RelatorioVendasSimples), @"mvc.1.0.view", @"/Areas/Admin/Views/AdminRelatorioVendas/RelatorioVendasSimples.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\_ViewImports.cshtml"
using PizzApp;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\_ViewImports.cshtml"
using PizzApp.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\_ViewImports.cshtml"
using PizzApp.ViewModels;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\_ViewImports.cshtml"
using ReflectionIT.Mvc.Paging;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"0a00cff60e6561b20225a30caa7a12c5d7ac4107", @"/Areas/Admin/Views/AdminRelatorioVendas/RelatorioVendasSimples.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"86d900cff8df954a9392b15bad9c8573d50334fc", @"/Areas/Admin/Views/_ViewImports.cshtml")]
    #nullable restore
    public class Areas_Admin_Views_AdminRelatorioVendas_RelatorioVendasSimples : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<IEnumerable<PizzApp.Models.Pedido>>
    #nullable disable
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("navbar-form navbar-left"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n<h2>Pedidos Por Período</h2>\r\n\r\n<nav class=\"navbar navbar-dark\">\r\n    <div class=\"container-fluid\">\r\n        ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "0a00cff60e6561b20225a30caa7a12c5d7ac41074376", async() => {
                WriteLiteral("\r\n            <div class=\"form-group\">\r\n                <div class=\"form-group\">\r\n                    <label for=\"minDate\">Data Inicial</label>\r\n                    <input type=\"date\" class=\"form-control\" name=\"minDate\"");
                BeginWriteAttribute("value", " value=", 411, "", 438, 1);
#nullable restore
#line 11 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
WriteAttributeValue("", 418, ViewData["minDate"], 418, 20, false);

#line default
#line hidden
#nullable disable
                EndWriteAttribute();
                WriteLiteral(" />\r\n                </div>\r\n                <div class=\"form-group\">\r\n                    <label for=\"maxDate\">Data Final</label>\r\n                    <input type=\"date\" class=\"form-control\" name=\"maxDate\"");
                BeginWriteAttribute("value", " value=", 644, "", 671, 1);
#nullable restore
#line 15 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
WriteAttributeValue("", 651, ViewData["maxDate"], 651, 20, false);

#line default
#line hidden
#nullable disable
                EndWriteAttribute();
                WriteLiteral(" />\r\n                </div>\r\n            </div>\r\n            <button type=\"submit\" class=\"btn btn-success\">Filtrar</button>\r\n        ");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_0);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n    </div>\r\n</nav>\r\n<div class=\"panel panel-primary\">\r\n    <div class=\"panel-heading\">\r\n        <h3 class=\"panel-title\">Total de Pedidos = ");
#nullable restore
#line 24 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                                              Write(Model.Count());

#line default
#line hidden
#nullable disable
            WriteLiteral("</h3>\r\n        <h3 class=\"panel-title\">Total de Itens nos Pedidos = ");
#nullable restore
#line 25 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                                                        Write(Model.Sum(obj => obj.TotalItensPedido).ToString());

#line default
#line hidden
#nullable disable
            WriteLiteral("</h3>\r\n        <h3 class=\"panel-title\">Valor Total dos Pedidos = ");
#nullable restore
#line 26 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                                                     Write(Model.Sum(obj => obj.PedidoTotal).ToString("c"));

#line default
#line hidden
#nullable disable
            WriteLiteral("</h3>\r\n    </div>\r\n    <div class=\"panel-body\">\r\n        <table class=\"table table-striped table-hover\">\r\n            <thead>\r\n                <tr class=\"success\">\r\n                    <th>\r\n                        ");
#nullable restore
#line 33 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                   Write(Html.DisplayNameFor(model => model.PedidoId));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                    </th>\r\n                    <th>\r\n                        ");
#nullable restore
#line 36 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                   Write(Html.DisplayNameFor(model => model.Nome));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                    </th>\r\n                    <th>\r\n                        ");
#nullable restore
#line 39 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                   Write(Html.DisplayNameFor(model => model.Email));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                    </th>\r\n                    <th>\r\n                        ");
#nullable restore
#line 42 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                   Write(Html.DisplayNameFor(model => model.Telefone));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                    </th>\r\n                    <th>\r\n                        ");
#nullable restore
#line 45 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                   Write(Html.DisplayNameFor(model => model.PedidoTotal));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                    </th>\r\n                    <th>\r\n                        ");
#nullable restore
#line 48 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                   Write(Html.DisplayNameFor(model => model.TotalItensPedido));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                    </th>\r\n                    <th>\r\n                        ");
#nullable restore
#line 51 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                   Write(Html.DisplayNameFor(model => model.PedidoEntregueEm));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                    </th>\r\n                </tr>\r\n            </thead>\r\n            <tbody>\r\n");
#nullable restore
#line 56 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                 foreach (var item in Model)
                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <tr>\r\n                        <td>\r\n                            ");
#nullable restore
#line 60 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                       Write(Html.DisplayFor(modelItem => item.PedidoId));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                            ");
#nullable restore
#line 63 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                       Write(Html.DisplayFor(modelItem => item.Nome));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                            ");
#nullable restore
#line 66 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                       Write(Html.DisplayFor(modelItem => item.Email));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                            ");
#nullable restore
#line 69 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                       Write(Html.DisplayFor(modelItem => item.Telefone));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                            ");
#nullable restore
#line 72 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                       Write(Html.DisplayFor(modelItem => item.PedidoTotal));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                            ");
#nullable restore
#line 75 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                       Write(Html.DisplayFor(modelItem => item.TotalItensPedido));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                            ");
#nullable restore
#line 78 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                       Write(Html.DisplayFor(modelItem => item.PedidoEntregueEm));

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n");
#nullable restore
#line 81 "C:\Users\leh_p\source\repos\PizzApp\PizzApp\Areas\Admin\Views\AdminRelatorioVendas\RelatorioVendasSimples.cshtml"
                }

#line default
#line hidden
#nullable disable
            WriteLiteral("            </tbody>\r\n        </table>\r\n    </div>\r\n</div>");
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IEnumerable<PizzApp.Models.Pedido>> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
